
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: New
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "7890:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django-app:
    container_name: django-app
    restart: always
    build: .
    ports:
      - "7777:8000"
    depends_on:
      - postgres
  adminer2:
    image: adminer
    restart: always
    container_name: adminer2
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
